# Generated by Django 3.2 on 2021-04-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meisteryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='product_sold',
            field=models.TextField(blank=True, null=True),
        ),
    ]
