# Generated by Django 3.2 on 2021-04-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meisteryapp', '0002_alter_user_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
